In [ ]:
import numpy as np

In [15]:

list_1d = [1, 2, 3, 4, 5]
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array_1d = np.array(list_1d)
array_2d = np.array(list_2d)

print(f"Одномерный массив из списка {list_1d}:")
print(f"  {array_1d}")
print(f"\nДвумерный массив из вложенного списка:")
print(f"  {array_2d}")


Одномерный массив из списка [1, 2, 3, 4, 5]:
  [1 2 3 4 5]

Двумерный массив из вложенного списка:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:

zeros_array = np.zeros((3, 4))
print(f"Массив 3x4 из нулей:\n{zeros_array}")

Массив 3x4 из нулей:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:

ones_array = np.ones((2, 3))
print(f"\nМассив 2x3 из единиц:\n{ones_array}")


Массив 2x3 из единиц:
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:

arange_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print(f"\nМассив с arange(0, 10, 2): {arange_array}")


Массив с arange(0, 10, 2): [0 2 4 6 8]


In [7]:

linspace_array = np.linspace(0, 1, 5)  # 5 точек от 0 до 1
print(f"Массив с linspace(0, 1, 5): {linspace_array}")

Массив с linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [11]:

identity_matrix = np.eye(3)
print(f"\nЕдиничная матрица 3x3:\n{identity_matrix}")



Единичная матрица 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:

print(f"\nДля массива:\n{array_2d}")
print(f"Форма (shape): {array_2d.shape}")
print(f"Тип данных (dtype): {array_2d.dtype}")
print(f"Размерность (ndim): {array_2d.ndim}")
print(f"Общее количество элементов (size): {array_2d.size}")


Для массива:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма (shape): (3, 3)
Тип данных (dtype): int32
Размерность (ndim): 2
Общее количество элементов (size): 9


In [16]:
test_array = np.array([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10],
                       [11, 12, 13, 14, 15],
                       [16, 17, 18, 19, 20]])

print(f"\nИсходный массив 4x5:")
print(test_array)


Исходный массив 4x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(f"  test_array[0, 0] = {test_array[0, 0]}")
print(f"  test_array[2, 3] = {test_array[2, 3]}")
print(f"  test_array[-1, -1] = {test_array[-1, -1]} (последний элемент)")


  test_array[0, 0] = 1
  test_array[2, 3] = 14
  test_array[-1, -1] = 20 (последний элемент)


In [18]:
print(f"  {test_array[1:3, :]}")


  [[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
print(f"  {test_array[:, 2:4]}")

  [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


In [20]:
print(f"  {test_array[1:4, 1:3]}")


  [[ 7  8]
 [12 13]
 [17 18]]


In [21]:
print(f"  {test_array[::2, ::2]}")

  [[ 1  3  5]
 [11 13 15]]


In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(f"  Сложение: {arr1} + {arr2} = {arr1 + arr2}")
print(f"  Умножение: {arr1} * {arr2} = {arr1 * arr2}")
print(f"  Возведение в степень: {arr1} ** 2 = {arr1 ** 2}")


  Сложение: [1 2 3 4 5] + [10 20 30 40 50] = [11 22 33 44 55]
  Умножение: [1 2 3 4 5] * [10 20 30 40 50] = [ 10  40  90 160 250]
  Возведение в степень: [1 2 3 4 5] ** 2 = [ 1  4  9 16 25]


In [24]:
scalar = 3
print(f"\n  Операции со скаляром ({scalar}):")
print(f"  Умножение на скаляр: {arr1} * {scalar} = {arr1 * scalar}")
print(f"  Сложение со скаляром: {arr1} + {scalar} = {arr1 + scalar}")


  Операции со скаляром (3):
  Умножение на скаляр: [1 2 3 4 5] * 3 = [ 3  6  9 12 15]
  Сложение со скаляром: [1 2 3 4 5] + 3 = [4 5 6 7 8]


In [25]:
stats_array = np.array([2, 5, 8, 10, 12, 15, 18, 20, 22, 25])
print(f"\nМассив для статистики: {stats_array}")

print(f"  Среднее значение (mean): {np.mean(stats_array):.2f}")
print(f"  Медиана (median): {np.median(stats_array):.2f}")
print(f"  Стандартное отклонение (std): {np.std(stats_array):.2f}")
print(f"  Дисперсия (var): {np.var(stats_array):.2f}")
print(f"  Минимальное значение (min): {np.min(stats_array)}")
print(f"  Максимальное значение (max): {np.max(stats_array)}")
print(f"  Сумма всех элементов (sum): {np.sum(stats_array)}")


Массив для статистики: [ 2  5  8 10 12 15 18 20 22 25]
  Среднее значение (mean): 13.70
  Медиана (median): 13.50
  Стандартное отклонение (std): 7.20
  Дисперсия (var): 51.81
  Минимальное значение (min): 2
  Максимальное значение (max): 25
  Сумма всех элементов (sum): 137


In [28]:
print(f"  Среднее по столбцам (axis=0): {np.mean(test_array, axis=0)}")
print(f"  Среднее по строкам (axis=1): {np.mean(test_array, axis=1)}")


  Среднее по столбцам (axis=0): [ 8.5  9.5 10.5 11.5 12.5]
  Среднее по строкам (axis=1): [ 3.  8. 13. 18.]
